# Generated by Django 5.0.1 on 2024-01-06 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Enqueued'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('busy', 'Busy'), ('no-answer', 'No Answer'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('to', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=5, default=-1, max_digits=10)),
                ('duration', models.SmallIntegerField(blank=True, default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'call',
                'verbose_name_plural': 'calls',
            },
        ),
    ]
